### ISSUE TITLE
Consider the cost of this project.

### ISSUE THREAD

**Issue by jsirois** [timgates42/meticulous#129]
I filed as a bug although this is more just an observation. As noted in https://github.com/pantsbuild/pants/pull/11402#issuecomment-753032506 there is a real cost to automated typo fixes. I just want to make sure you've evaluated that cost and still determined this is a net positive. If so, it might be good to update https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md with a few sentences acknowledging the cost and noting how the cost is more than offset by the good you perceive resulting from the automated PRs.

**Comment by timgates42** [comment]
Thanks @jsirois for pointing this out - for a while I’ve been thinking of adjusting the UI so I can work on multiple typos in a single PR not for the CI cost but to save review time which is another cost. I’ll work on that next so that I can fix something more substantial with each PR which I think should help with these concerns?

**Comment by Eric-Arellano** [comment]
Another idea that may help: open a concise issue with the project first to check with the owners if they are open to a PR. In Pants, someone made a very similar automated typo fix last year, so there was almost nothing left to fix with your PR.

Generally, with open source, I've found it's very helpful to open an issue before submitting the sibling pull request. It helps save everyone time because the maintainers can point things out early.

**Comment by jsirois** [comment]
Yeah, an issue is the key. Your automation could include all the suggested typo fixes in the issue, even pointing to a non-pr branch using permalinks.

With that, everything is ready to go if the project maintainers want the contrib. That nicely sidesteps the whole issue of whether the typo fixes are actually a net positive.

**Comment by timgates42** [comment]
Thanks @jsirois and @Eric-Arellano an issue and non-pr branch all setup sounds like an excellent idea

**Comment by timgates42** [comment]
Just for some feedback in case you were wondering what happened to your great idea. I've stopped submitting new PRs and was implementing this when I noticed CI was failing, when I investigated it I noticed the CI was picking up a spelling mistake in files included while running coverage so I'm trying out the new approach manually of creating a branch ready to go with an issue linked to a branch ready to go - https://github.com/nedbat/coveragepy/issues/1092

**Comment by jsirois** [comment]
Beautiful. Thanks @timgates42.
